### ISSUE TITLE
Code Release of Neo-360

### ISSUE THREAD

**Issue by thucz** [zubair-irshad/NeO-360#1]
Hi! This is a great work! I'm recently investigating efficient generalizable NeRF. My research is highly related to NeO-360. I really appreciate this work and would like to do my research based on it! When do you plan to release the whole code?

**Comment by zubair-irshad** [comment]
Thanks for your interest in our work. We are in the process of cleaning the codebase for release, please bear with us as the code release will be close to the ICCV conference date, thank you!

**Comment by EchoTHChen** [comment]
Thanks so much!

**Comment by thucz** [comment]
Hi! Is there any progress about the code release?

**Comment by flymin** [comment]
Looking forward to the code release. Thank you.

**Comment by Louis-Leee** [comment]
Looking forward to the code release. Thank you.

**Comment by EchoTHChen** [comment]
Could you release the code a bit earlier?
