### ISSUE TITLE
How to mitigate the CUDA-error: Out-of-memory?

### ISSUE THREAD

**Issue by thucz** [zubair-irshad/NeO-360#10]
Hello! Since I have only 4 A100 available now, I reduced the chunk size from 16*64 to 256. But Out-of-memory error still appears, do you have any idea to fix it?

**Comment by thucz** [comment]
I found even I used 8 A100 card with your given parameters: chunk size 16*64, the error still happened.

**Comment by zubair-irshad** [comment]
I am only able to check currently with 7 GPUs and the training runs fine, can you share your gpu utilization? Mine is shared below and it utilizes around 40GB memory per gpu. This is with using `chunk size = 16 * 64`

<img width="256" alt="image" src="https://github.com/zubair-irshad/NeO-360/assets/32943733/90ac8396-7d4a-4a81-826d-eaaba66e8331">

**Comment by zubair-irshad** [comment]
Here is my training progression:

<img width="682" alt="image" src="https://github.com/zubair-irshad/NeO-360/assets/32943733/07d96711-c400-4709-a53f-ec42e3d5f1dd">

**Comment by thucz** [comment]
<img width="1775" alt="image" src="https://github.com/zubair-irshad/NeO-360/assets/135981918/eab9df4b-a71b-4c6d-8f00-bc4535508105">

I use `watch -n1 nvidia-smi` to observe the gpu utilization. It reached 40G and then crashed.

Even I used chunk size 512 with 8A100 GPUs, OOM still happened.

Do you have any advice to reduce GPU memory?

**Comment by thucz** [comment]
I changed a docker image with CUDA11.3. The code can run normally. Previously I used the docker image with CUDA11.7. Sorry for bothering you.

**Comment by thucz** [comment]
> I changed a docker image with CUDA11.3. The code can run normally. Previously I used the docker image with CUDA11.7. Sorry for bothering you.

But I still wonder how to reduce GPU memory because I want to run it on other Cards like V100 (32GB)

**Comment by thucz** [comment]
Just now I found that It utilized about 58G per GPU on 80G A100 cards. It is so weird.

<img width="626" alt="image" src="https://github.com/zubair-irshad/NeO-360/assets/135981918/482e9b3d-f935-41eb-b7cc-3b056d033a39">

**Comment by zubair-irshad** [comment]
Great to know that you have the code working on your end on A100 GPUs. To further reduce the memory, you can try the following:

1. We randomly sample [500 rays](https://github.com/zubair-irshad/NeO-360/blob/master/datasets/nerds360_ae.py#L535) from [20 destination views](https://github.com/zubair-irshad/NeO-360/blob/master/datasets/nerds360_ae.py#L566) for rendering the target pixels. You could try reducing either of these to reduce memory. Please note that 500 is already a very low number, so I would suggest playing with the other parameter i.e. num_destination views first. 

2. Our data loader needs some refactoring. Currently, we load all annotations i.e. [NOCS maps, instance maps](https://github.com/zubair-irshad/NeO-360/blob/master/datasets/nerds360_ae.py#L616-L618). This might reduce some memory, but not that much. 

4. One could of course reduce the `img_size` to train and fine-tune with a higher resolution. 

5. I tried to improve [grid sampling](https://github.com/zubair-irshad/NeO-360/blob/master/models/neo360/encoder_tp_fusion_conv.py#L180) which is probably the part that requires the most memory in a single forward pass, and we have some batchifying code commented [here](https://github.com/zubair-irshad/NeO-360/blob/master/models/neo360/encoder_tp_fusion_conv.py#L144-L158) which was a WIP and never truly trested. Please feel free to also give this a try, but note that we have not benchmarked our numbers with this batchification. 

All of the above, we have not tried on our end locally, so we haven't benchmarked the exact memory savings they would generate, but please feel free to give these a try and let us know how it goes. Hope it helps your research!

**Comment by thucz** [comment]
Thanks a lot! I will try your advice.
