### ISSUE TITLE
Can Neo360 synthesize novel view from frontal camera images

### ISSUE THREAD

**Issue by haiphamcse** [zubair-irshad/NeO-360#11]
Hi there, loved your work. I was wondering whether Neo360 can take source views from frontal images, similar to setups in nuScenes and KITTI? 
![image](https://github.com/zubair-irshad/NeO-360/assets/76871780/fcf467a0-6b44-4e2f-90af-adad6b680f74)

**Comment by zubair-irshad** [comment]
Hi @haiphamcse, Thanks for your question. Please see Figure 14 in our paper: https://arxiv.org/pdf/2308.12967.pdf where we adapted our network to work on Kitti360 dataset. We gave our method a source view window of the last 3 frames to render the subsequent frame.  

While our method is only designed for a 360-degree setting, one could certainly fine-tune it or train it from scratch for the use case you are describing. To train such a model, one can define the training objective in a way that is suitable for our architecture i.e. given some source views, we can decode from a novel target view and enforce a photometric consistency loss. Let me know if this is helpful and if you have any other questions. 

![image](https://github.com/zubair-irshad/NeO-360/assets/32943733/21b9aa86-7390-46b8-869d-08099b5bf8da)
