### ISSUE TITLE
Intrinsics missing

### ISSUE THREAD

**Issue by F-Barto** [zubair-irshad/NeO-360#3]
Dear authors,

Thank you very much for sharing your dataset.
It seems to me that the intrinsics are missing ?

**Comment by zubair-irshad** [comment]
Thanks, @F-Barto for your interest in our work. We will be releasing our data loading script which details how to load focal length but here is a quick way to retrieve focal length and principal point for our rendered images:

```
pose_file_train = os.path.join(pose_dir_train, "pose.json")
with open(pose_file_train, "r") as read_content:
    data = json.load(read_content)
focal = data["focal"]
where f_x = f_y = focal
```

principal points are simply determined as follows:
```
c = np.array([640 / 2.0, 480 / 2.0])
and c_x =c[0] and c_y = c[1]
```

where 

```
K = | f_x  0   c_x |
    |  0  f_y  c_y |
    |  0   0    1  |

```

of course, you can scale focal length and principal point accordingly, if you are using a downsampled version of the images for your use-case. Hope it helps!

**Comment by F-Barto** [comment]
Thank you very much for your response !

Indeed ! I just printed pose.json instead of looking at its keys.

```python
import json

with open('PDMultiObjv6/train/SF_GrantAndCalifornia5/train/pose/pose.json', 'r') as f:
    data = json.load(f)
    print(data.keys())

>>> dict_keys(['transform', 'obj_location', 'focal', 'bbox_dimensions', 'obj_translations', 'obj_rotations', 'fov', 'img_size'])
```

It contains much more than I expected (and everything I need).

Have a good day !
