### ISSUE TITLE
Axes convention

### ISSUE THREAD

**Issue by F-Barto** [zubair-irshad/NeO-360#5]
Hi again !

Could you share the axes convention you used for the world and the cameras ?

For example:
    - the x-axis is pointing to the camera's right
    - the y-axis is pointing to the camera's forward
    - the z-axis is pointing to the camera's upward
    
Have a good day !

**Comment by F-Barto** [comment]
Ok I see, that's what I suspected. Is there a reason for this choice?

> Optionally before converting it to OpenGL, you could consider canonicalizing the poses so they are centered at origin
What is `obj_location`, the position of one of the car in the scene?

For now I am setting the world origin as the average of the cameras position on the x and y axes and keeping the z-axis value as 0

Thank you for your availability :)

**Comment by zubair-irshad** [comment]
Correct, it is the center of the hemisphere used to generate camera poses. averaging the x/y axes values should also work the same way. For overfitting it probably shouldn't matter as much but for generalizability this should remove any biases in camera locations in world coordinates. 

Other than this, it is a good practice to do [pca](https://github.com/google-research/multinerf/blob/5b4d4f64608ec8077222c52fdf814d40acc10bc1/internal/camera_utils.py#L191) on the poses which should give you similar results.
