### ISSUE TITLE
Cameras in ground or objects

### ISSUE THREAD

**Issue by F-Barto** [zubair-irshad/NeO-360#6]
Hello !

Just to let you and future user know that sometimes (very rarely) a camera may be partially in the ground or an object (e.g., a trash bin).

Example with PDMultiObjv6/train/SF_VanNessAveAndTurkSt8/train/instance_segmentation_2d/midsize_sedan_04_emg_01-006.png

![midsize_sedan_04_emg_01](https://github.com/zubair-irshad/NeO-360/assets/905829/7ebd8e21-f3c4-47bd-a40a-8131026833e2)

**Comment by zubair-irshad** [comment]
Thank you for the note. We are aware of this and tried our best to mitigate collisions with the side objects using a larger field of view and smaller radius of hemisphere. 

Still in some rare cases, there might be some collisions and you could choose to omit it for your specific use cases i.e. novel view synthesis or depth/instance/3D OBB predictions etc.
